# Generated by Django 2.2.3 on 2019-07-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_champions_organiser_tc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championsTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Champions')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Team')),
            ],
        ),
    ]
