# Generated by Django 2.2.3 on 2019-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cash on desk', 'Cash on desk')], default='Unpaid', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
