# Generated by Django 2.2.3 on 2019-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20190724_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Status',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('DISQualified', 'DISQualified'), ('Pendinng', 'Pendinng'), ('Finish', 'Finish')], default='Pendinng', max_length=40),
        ),
    ]
